### ISSUE TITLE
[Bug][macOS]: No option to move podcast to top level

### ISSUE THREAD

**Issue by verumsolum** [gdavis/Mimir-Feedback#101]
### Are you sure this is a new issue?

- [X] I have confirmed this is a new issue

### macOS Version

Monterey 12.3.1

### Your Mac

Mac mini (M1, 2020)

### App Version

1.5.0 (110)

### What happened?

Right click on podcast within a folder in left-hand sidebar. Move to option allows moving to another folder, but not moving back to the top-level (i.e., outside all folders). (Workaround was to click-and-drag podcast down to the top-level list.)

### Add screenshots or video

![image](https://user-images.githubusercontent.com/14137011/163370996-9be65bbf-4d10-43d5-a7b5-30d1740c3255.png)

**Comment by gdavis** [comment]
Hi @verumsolum! This is a good suggestion, and I agree it should be an option in the context menu. I'll put it in the queue to be worked on 👍

**Comment by gdavis** [comment]
This feature has been added and will be in the next beta release. Thanks for the feedback @verumsolum!
