### ISSUE TITLE
[Bug][iOS]: Could not download episode

### ISSUE THREAD

**Issue by elmoritz** [gdavis/Mimir-Feedback#102]
### Are you sure this is a new issue?

- [X] I have confirmed this is a new issue

### iOS Version

15.4.1

### Device Model

iPhone 13 pro max

### App Version

1.0.0 (84)

### What happened?

I tried to play an episode that was not downloaded, at a place where the internet wasn't very good.

### How does it happen?

Playback Error
Mimir has failed to play the current episode. There may be an issue with the file, the network, or some other bug causing the issue.

Please try again or if the problem persists, report the issue to support@mimirpodcasts.app with the error below.

Player Error:
The request timed out.

Device Info:
App Version:    1.0.0
Build:          84
Device:         Elmo’s iPhone
Device Model:   iPhone
OS Version:     15.4.1
Locale:         en_DE
Language:       en

### Anything else?

I don't think it is a bug. It should be reported to the user, but it is not a bug. This can happen.

**Comment by gdavis** [comment]
Hey @elmoritz! So is the issue here that the episode was not downloaded on a spotty network? Or that the error message should be better? If you saw a 'timed out' error popup, it sounds like the episode failed to load because of the bad network conditions. What would you like to see changed here?

**Comment by elmoritz** [comment]
Hi @gdavis,
as a user I expect that if the download failed due to bad Connection, I receive a message, that I should trigger the download again.
But instead I got a bug report message, which I think is a little over the top, since you can not fix the issue.

😇

**Comment by gdavis** [comment]
Sounds good! Will add it to the queue.

**Comment by gdavis** [comment]
@elmoritz I added some error detection here so you'll see some better error messages when the network connection fails. Thanks again for reporting!
