### ISSUE TITLE
[Bug][iOS][macOS]: Playback stuck in infinite-loop

### ISSUE THREAD

**Issue by elmoritz** [gdavis/Mimir-Feedback#106]
### Are you sure this is a new issue?

- [x] I have confirmed this is a new issue

### iOS Version

15.4.1

### Device Model

iPhone 13 Pro Max

### App Version

1.0.0 (84)

### What happened?

I listen to a podcast and when it is suppose to end and jump to the next podcast in the list, it will continue in an infinite-loop.

The timeline jumps from 0sec remaining to 5sec remaining in an infinite-loop and will only jump to the next episode by force(tapping next episode)

### Bug prevalence

not always, but very often

### How does it happen?

1. add more episodes to play in the queue and start playing an episode 
2. wait for the episode to play till the end
3. observe

It happens all the time, that I have to force jump to the next episode, since it is stuck in this infinite loop.

**Comment by gdavis** [comment]
I've been tracking this one for a bit internally as well and is the highest priority issue in the audio player. I'll be working on fixing this right after I resolve the issues with iCloud sync.

**Comment by gdavis** [comment]
Also being tracked here: gdavis/Mimir#778

**Comment by elmoritz** [comment]
I have noticed something.
This only happens when the podcast ends with a longer silence. 
Maybe your algorithm tries to skip beyond the end of the file.
Just a thought.

**Comment by gdavis** [comment]
@elmoritz are you always connected to a bluetooth device, like airpods, when this happens? If can also let me know the episode and podcast that this next happens to you on, please let me know. I'm still working on getting this issue to reproduce consistently in a test environment so I can diagnose how it happens

**Comment by elmoritz** [comment]
@gdavis I will post again when it happens with the information on which podcast it occurred. 
As for the bluetooth part. I always listen to podcasts either on the AirPods pro, the homePod Mini or in the Car(standard bluetooth connection).
As far as I can tell it does not matter what device is connected, but I have not used Mimir without accessory

**Comment by elmoritz** [comment]
@gdavis I just had it happen to me.
it was on the latest episode from MPU (from [relay.fm](https://www.relay.fm/mpu))
Title: #638: A Mac Setup Consulting Company
Podcast: Mac Power Users
Link: https://www.relay.fm/mpu/638

**Comment by gdavis** [comment]
Okay thanks for the extra info @elmoritz.

I'm finding even episodes that have previously gotten stuck doesn't mean they'll get stuck every time. Still trying to get to the bottom of what makes this happen…

**Comment by gdavis** [comment]
@elmoritz are you typically downloading episodes when you play them? Or are you streaming the file when this issue happens? I have different loaders and might be happening just for one. My hunch is this happens when the file has not been downloaded to the device?

**Comment by elmoritz** [comment]
@gdavis I usually download the episodes in the morning and listen to the episodes on the way.

**Comment by gdavis** [comment]
Hey @elmoritz, the latest version of Mimir snuck in a test fix for this issue. Have you by chance still been experiencing this issue at all?

**Comment by gdavis** [comment]
Unfortunately had this happen again this past week while connected to bluetooth speakers. Still unsure how to reproduce. Going to try and run the app open for a few hours just going through episodes to see if I can get it in this state with the debugger running so I can capture it

**Comment by gdavis** [comment]
Possible clue: this happened while in the car and had an episode where the playhead was past the duration. e.g. player was at -0:00 for a minute or more while the episode finished out. Once it hit end of audio data, the player hung. Episode in question: `Kinda Funny Games: E3 2023 vs Summer Game Fest (7.7.2022)`

**Comment by gdavis** [comment]
The problem:
The player reaches the end of the file and the player node gets stuck in a "stalled" `bufferingState`.  This leads the the player state reducer entering a "loading" state for the player. 

The fix:
Need to call `updateBufferState` to get the player node into the correct buffering state. Find out why it is not being called when we expect, any why it is so intermittent.

**Comment by gdavis** [comment]
@elmoritz I've just released a new version that hopefully will fix this problem. Please give it a shot if you're still testing and let me know if this happens again!

Going to keep this issue open for a few days while I validate if it is really fixed

**Comment by gdavis** [comment]
So far I have not seen this issue reoccur in the last few days of testing. With today's app release, I'm going to close this issue until I get new reports of it occurring. But hopefully never reopen.

**Comment by gdavis** [comment]
Still happening 😞

**Comment by gdavis** [comment]
Released another potential fix today in version 1.0.4 for iOS, and 1.5.2 for macOS. 

This is a tricky one without totally reworking the state management for the player. Added a possible fix today that should resolve this until I can do a more holistic rework of the problematic area.

**Comment by gdavis** [comment]
New version introduced other issues, such as skipping a track before it finishes playing. Need to send this one back to the drawing board.

**Comment by gdavis** [comment]
This has been fixed in version 2 of the audio player. It will be part of the next TestFlight release which should be in testing in the next few days.

**Comment by gdavis** [comment]
The new audio player update is now available for both platforms in TestFlight.

@elmoritz please let me know if you have time to give the new version a test with the player fixes. Sorry this took so long for me to fix, I had to totally gut and refactor much of the player while also working a contract job. Now its using a much more stable state model that I'm really excited about and think the player is in a much more polished state.
