### ISSUE TITLE
[iOS] Episode notes

### ISSUE THREAD

**Issue by elmoritz** [gdavis/Mimir-Feedback#112]
**Is your feature request related to a problem? Please describe.**
It is not a problem, but a nice feature to have. I come across a lot of episodes which put a link in the description.
Right now it looks like the description is the general description for the Podcast and not the Episode description.
Since there might be interesting links in it, it would be nice to make them interact-able(tapable).

**Comment by gdavis** [comment]
I'm a little confused on this one, episodes notes pull the episode description from the RSS feed. The Now Playing episode details and episode detail view both will use this episode description text. There also is link detection already in place, so links should be interactive from these views. The only place the podcast description appears is in the podcast detail view where it also shows all episodes in a podcast.

Can you post some screenshots to show what you're talking about?

**Comment by gdavis** [comment]
@elmoritz just checking to see if you can still show a podcast where you're seeing the wrong descriptions. Thanks!

**Comment by elmoritz** [comment]
@gdavis I guess I found a few episodes, which did not have any description.
Sorry for this.

You can close it. 
It was my mistake, since I tried to look into the description and get some info from the episode, but the creator did not provide it.

**Comment by gdavis** [comment]
Sounds good! Thanks for looking into this @elmoritz
