### ISSUE TITLE
[iOS] [feature] Make the Audio-output-Menu accessible from with in the App/Player 

### ISSUE THREAD

**Issue by elmoritz** [gdavis/Mimir-Feedback#119]
**Is your feature request related to a problem? Please describe.**
Normally when I use the App I want to listen to it with my AirPods Pro or a combination of HomePod minis.
It would be nice to have the Menu to assign the output device right in the App/Player.

**Describe the solution you'd like**
Have a button in the Player to assign the correct output Device right within the Player.

**Comment by gdavis** [comment]
This is a great feature to add, I agree. I don't think it'll make the cut for the initial release of the app though, but will likely come in a later update. I'm really trying to limit the scope of the 1.0 version of the iOS app so it actually gets finished :) 

Keeping in the backlog for now.

**Comment by gdavis** [comment]
Bumping this up in priority. This feature has gotten a few requests now, so we'll slate this feature to get added into the next update.

**Comment by gdavis** [comment]
This has been implemented and will be available in the next release. Sorry about the delay on this, I wanted to fix issues with the player before adding more functionality such as this.
