### ISSUE TITLE
[BUG][macOS] Possible image caching problem when changing screens (see video attached)

### ISSUE THREAD

**Issue by ileacristian** [gdavis/Mimir-Feedback#12]
While switching between screens like "Home", "Recommendations", "Search" etc. there seems like some images are not cached - since they flicker after i change between the screens - even after a second or two i can see another flicker.
Sometimes the hover doesn't work over some cells in the Recommendations list.

**Also, the main thread seems to block when quickly switching between screens.**

https://user-images.githubusercontent.com/705971/159778739-f650a1f4-37de-41a5-80f3-e473c00a7bc0.mov

**Comment by gdavis** [comment]
Tried to reproduce this issue today and could not get it to happen. I've made a lot of changes to the image library that drives the code here over the past month or so, so I think this was solved as part of those changes. Going to go ahead and close it.
