### ISSUE TITLE
[Bug][macOS]: iCloud Error (CKErrorDomain error 7.)

### ISSUE THREAD

**Issue by SurlySteve** [gdavis/Mimir-Feedback#129]
### Are you sure this is a new issue?

- [X] I have confirmed this is a new issue

### macOS Version

Monterey 12.4

### Your Mac

iMac (21.5-inch, 2017)

### App Version

1.5.0 (116)

### What happened?

An episode is playing and this error message keeps appearing and will not clear.

### Bug prevalence

This is the forst time I've experienced this issue.

### Add screenshots or video

![Screen Shot 2022-06-07 at 6 12 04 AM](https://user-images.githubusercontent.com/102470092/172356833-608cc355-73ff-4c27-9da9-c894f0dd8a57.png)

**Comment by gdavis** [comment]
Thanks @SurlySteve. I dug into this and found that error 7 means the device is being rate limited by the server. Meaning the app is being slowed down from sending too many iCloud update requests. Was this after setting a bunch of episodes as played, or adding a new podcast or something?

Either way, I'll be adding some better error handling around these error codes and only present errors when the error is serious enough to interrupt sync completely. Rate limiting should resolve itself after some time. 

Thanks for reporting this!

**Comment by SurlySteve** [comment]
Hey Grant!

Other than playing episodes with Mimir my iMac was doing nothing other than possibly receiving e-mail, I did notice some lagginess with switching between application on my iMac later.  I use Mimir on my iMac while teleworking with my work provided laptop.

Cheers!

Steve
