### ISSUE TITLE
[Bug][macOS]: I would prefer toggles that are enabled to be purple

### ISSUE THREAD

**Issue by ileacristian** [gdavis/Mimir-Feedback#14]
I would prefer that player toggles that are enabled (like voice boost and silence skip) to be highlighted in purple when enabled - it seems like on the upcoming iOS app it's like that. On the macOS app they seem to be dimmed out when disabled.

This is also inconsistent with the toggles in the podcast settings section:
-silent skip doesn't stay purple when "always on" is selected
-subscribe "enabled" is purple when enabled
-notifications "enabled" is purple

**Comment by gdavis** [comment]
Context: this is in reference to the player controls buttons in the Now Playing UI (not in preferences)
