### ISSUE TITLE
[Bug][macOS]: Episode missing from Top Priority Episodes list while present in Continuous Play queue

### ISSUE THREAD

**Issue by verumsolum** [gdavis/Mimir-Feedback#146]
### Are you sure this is a new issue?

- [X] I have confirmed this is a new issue

### macOS Version

Monterey 12.4

### Your Mac

Mac mini (M1, 2020)

### App Version

1.5.0 (118)

### What happened?

While playing episodes, I noticed that the Top Priority Episodes and Continuous Play lists didn't match. An episode of Our Opinions Are Correct was missing from the TPE list, while it appears in the CP list. I waited to see what would happen after I started the next episode from the list, and it was still missing. (The second screenshot also notes an instance of #137 occurring at the same time.)
<img width="1578" alt="image" src="https://user-images.githubusercontent.com/14137011/174044966-5c9e5305-5bfd-4188-abd1-3962d6d6124f.png">
<img width="1578" alt="image" src="https://user-images.githubusercontent.com/14137011/174045063-8fbadcd8-42a0-4e5d-8628-15cf21240f99.png">

### Bug prevalence

Only noticed this one time

**Comment by gdavis** [comment]
Hi @verumsolum, can you include a screenshot of the Continuous Playback settings you have for this? Depending on what your settings are, those two sections of episodes may not always match up.

**Comment by verumsolum** [comment]
The ones from Show Options? 
<img width="267" alt="image" src="https://user-images.githubusercontent.com/14137011/174088581-b8181c1c-dc9e-4596-8b1d-37718dbead63.png">

**Comment by gdavis** [comment]
Yep, exactly what I was looking for. I didn't have time in this week's release to take a look at #137, but I'll take a look at whats happening there and in this issue next week. Thank you again for reporting issues!

**Comment by gdavis** [comment]
I have made some improvements around the logic for having these lists update as episodes are listened to, so the next release should solve some of the problems here.

The Top Priority list will not always be exactly the same as what is shown in the Continuous Playback list, however. The Continuous Playback list has a few more filtering steps where it will apply count limits for each podcast, and filter out episodes that have already been placed into the queue at some point. 

The Top Priority list is a bit dumber in that it only looks for episodes that have not yet been played or placed into the up next list, and has a non-default priority value. 

The next update should fix issues with the `played` value not being updated properly when listening to podcasts, so hopefully that'll take care of the main issues here. 

I'm going to close this for now and reopen if needed if the next release does not properly fix these issues.

**Comment by verumsolum** [comment]
I'm not sure whether to report here or open a new issue, but since 1.5.0(120), new episodes are not appearing in Top Priority, unless I manually add them to Up Next. They appear to be showing up properly in the Continuous Playback list, but after several days of using the new beta, nothing added to Mimir since then has appeared in Top Priority, unless I have dragged it from the Continuous Playback list up to the Up Next list, in which case the episode shows up in Top Priority list until it moves from Up Next to Playing.

**Comment by gdavis** [comment]
We'll go ahead and track this by reopening the issue here. I'll take another stab at this one this week.

**Comment by gdavis** [comment]
@verumsolum I found some issues today that made it so new episodes were not showing up properly. Should be much better in the next update!
