### ISSUE TITLE
[Bug][macOS]: Continuous Play - Hours acts the same as Episodes

### ISSUE THREAD

**Issue by verumsolum** [gdavis/Mimir-Feedback#149]
### Are you sure this is a new issue?

- [X] I have confirmed this is a new issue

### macOS Version

Monterey 12.4

### Your Mac

Mac mini (M1, 2020)

### App Version

1.5.0 (118)

### What happened?

When choosing how much to show in the Continuous Play list, using "Hours" doesn't appear to check length of podcasts, shows selected number of episodes instead.

### Add screenshots or video

[Video example](https://www.screencast.com/t/1uVaj6qv1), where multiple episodes could be listened to in an hour, but 1 Hour shows only a single episode (and no matter how many hours I choose, the list shows the number of episodes instead of the number of hours)

**Comment by gdavis** [comment]
@verumsolum I've found the issue on this one and added a fix for the next release. Thanks for reporting the issue!
