### ISSUE TITLE
[macOS] Ability to show current audio speed multiplier

### ISSUE THREAD

**Issue by ileacristian** [gdavis/Mimir-Feedback#15]
I would love to see the current speed multiplier somehow in the UI. Even on hover (tooltip) would work for me. 
I was expecting the the gauge needle pointing up is 1.0x but i think 1.0x is somewhere pointing "left".

**Comment by gdavis** [comment]
A tooltip is a good idea! I might also add a label like the iOS app next to the progress bar to show it persistently. The gauge needed is to the left because we have more faster speeds than slower speeds and I didn't want to have an equal number of both.
