### ISSUE TITLE
[Bug][iOS]: can’t import mimir or OPML library

### ISSUE THREAD

**Issue by cobaline** [gdavis/Mimir-Feedback#157]
### Are you sure this is a new issue?

- [X] I have confirmed this is a new issue

### iOS Version

15.5

### Device Model

iPhone 13 Mini

### App Version

1.0.0 (93)

### What happened?

i exported my Mimir MacOS library as both a Mimir and an OPML file. When I try and import the Mimir format, it is not selectable via the file uploader browser. When I try and import the OPML file, the import process fails silently.

### Bug prevalence

Every time I try

### Add screenshots or video.

https://share.icloud.com/photos/02cs38x_CQc4jvohBnULXkoOQ

**Comment by gdavis** [comment]
Hello @cobaline! Thanks for taking the time to make a bug report. The `plib` file is an older file type that is being replaced in the new version with the `mimirlibrary`. That said, it is a bug that it is not showing up on iPhone as a supported file type, which is an oversight on my part. I'll look at adding this support in today.

As for the OPML file, could you possibly attach a copy of that to this ticket so I can reproduce the issue using the exact same file? That's definitely a bug that I'll take a look at as well.

Thanks again for helping test!

**Comment by gdavis** [comment]
Hi @cobaline – I've added a fix today for importing the `plib` file types into the iOS app. This will be part of the next Testflight update.

The OPML import issue remains a mystery to me, I've tried exporting from Mimir macOS versions 1.4.2 and 1.4.4 and did not experience any issues trying to import those files. I'm going to open a new issue here to track import issues with OPML files: 
https://github.com/gdavis/Mimir-Feedback/issues/159

If you can attach your OPML file that is giving you trouble to that new ticket that would be amazing!
