### ISSUE TITLE
[Bug][Audio]: Episode failing to play

### ISSUE THREAD

**Issue by gdavis** [gdavis/Mimir-Feedback#180]
User report:

> I have an episode that isn't playing properly this morning in the macOS beta of Mimir [1.5.0 (123)] 
> 
> I'm emailing rather than posting on Github, because I'm not sure whether it's a Mimir bug or an error in the feed (especially as this 50-second episode is the first and only episode in the feed so far). 
> 
> I was able to find the Inside Jeopardy! podcast using the search feature inside the Mimir app and downloaded the first episode. 
> 
> When I attempt to listen to it, I receive an error popup of a Playback Error, the end of which suggests contacting you with: 
> Error: Data request is out of range of file. 
> 
> I used the "Show in Finder" right-click menu option to find the file, and when I played it through QuickTime Player. I did notice that it has a .m4a file extension rather than .mp3 and wondered whether that was a filetype Mimir expected or not.

- [ ] Determine if this is a supported file type
- [ ] Fix any possible audio engine bugs

**Comment by gdavis** [comment]
This is happening on this file because it is a "non-optimized" M4A AAC file. Being non-optimized means it does not include the header information at the start of the file, so determining the file format fails when trying to parse the file data. 

So far I'm unsure how to go about fixing this without having to convert the file when it is downloaded. Technically, this could be considered a feed error since the file is not optimized for streaming when serving an online podcast file. Ideally, we'd be able to work around this and get `AudioFileStreamOpen` to properly stream the file, even without optimized compression.

Some helpful information here:
https://stackoverflow.com/questions/23503117/fail-parsing-m4a-aac-file-with-apple-audio-file-stream-services-ios-7?answertab=scoredesc#tab-top

and here: 
https://www.cocoawithlove.com/2010/03/streaming-mp3aac-audio-again.html

**Comment by verumsolum** [comment]
Thank you for looking into this! Hopefully Sony gets their encoding working optimally for future episodes! And, at least the feed is good, so I can still use Mimir to know when there are new episodes, even if the episodes continue to be sent in the same format

**Comment by gdavis** [comment]
@verumsolum Hopefully since its a new feed its a mistake they will fix, or maybe we should contact their feed admin to let them know about this. If it continues to be a problem with future episodes they release, please let me know. Maybe I can escalate trying to figure out a fix for this on my end if it prevents the feed from being usable.

**Comment by verumsolum** [comment]
> @verumsolum If it continues to be a problem with future episodes they release, please let me know. Maybe I can escalate trying to figure out a fix for this on my end if it prevents the feed from being usable.

I will. I believe the first "full" episode is supposed to be released sometime today and weekly after that, so there shouldn't be too much wait to see what they release.

**Comment by verumsolum** [comment]
And the first full episode is playing properly through Mimir, so presumably the podcast's producers have made the appropriate change

**Comment by gdavis** [comment]
Ah, fantastic! I'll go ahead and close this issue in that case. Thanks for checking!
