### ISSUE TITLE
[BUG][iOS][UI] podcast episode header autolayout breaks when switching to a different app (see video)

### ISSUE THREAD

**Issue by ileacristian** [gdavis/Mimir-Feedback#19]
Steps to reproduce:
1. Go to an episode
2. Scroll down
3. Go to a different app and come back
4. Scroll up

Unexpected: header ui is broken

https://user-images.githubusercontent.com/705971/159798518-1dacb4af-8f86-44e9-913f-0210df233a76.MOV

**Comment by gdavis** [comment]
Wow that's a new one! Can you tell me what iOS version you are on for this?

**Comment by ileacristian** [comment]
> Wow that's a new one! Can you tell me what iOS version you are on for this?

i'm on iOS 15.4
