### ISSUE TITLE
[iOS]: Add support for skip forward/back via BTE headphones

### ISSUE THREAD

**Issue by gdavis** [gdavis/Mimir-Feedback#193]
From user feedback

> I’m not able to pause and resume or fast forward with Bluetooth headphones like I can with other podcast apps. Is this feature only available with a subscription? 
> 

I asked what headphones:
> Headphones are AirPods  pro and Beats flex. Both pause but don’t resume with another click. And I am unable to fast forward or rewind like I can with the fore mentioned apps.

**Comment by drallgood** [comment]
Yeah. I think FF and Rewind via system controls are in general not working properly. 
I've tried rewinding a couple of times but ultimately had to use the app to do it. It would not consistently jump back when tapping multiple times

**Comment by gdavis** [comment]
This fix has been made and will be available in TestFlight for testing soon. I hope to release on the store later this week.
