### ISSUE TITLE
[Bug][macOS]: Cannot import from Apple Podcast on Ventura

### ISSUE THREAD

**Issue by caramdache** [gdavis/Mimir-Feedback#196]
### Are you sure this is a new issue?

- [X] I have confirmed this is a new issue

### macOS Version

Ventura 13.0 beta 5

### Your Mac

MacBook Pro M1 14"

### App Version

1.5.1

### What happened?

1. When I try to import from Apple Podcast, a dialog box says there are no podcast to import (but here are)
2. When I try to import individual podcast files from a standard directory, the podcast are greyed out and cannot be selected.

### Bug prevalence

Always

### How does it happen?

1. Open the app
2. File/Import
3. Select from Apple Podcasts
4. Dialog box says there are no podcast to import

**Comment by gdavis** [comment]
Hi @caramdache, thank you for opening this issue.

For this point: 
> When I try to import individual podcast files from a standard directory, the podcast are greyed out and cannot be selected.

What do you mean here? Are you looking at podcast MP3 files? Or are they OPML or Mimir library files?

I have not yet checked validated Mimir on Ventura yet so it is possible there are bugs in the beta. I haven't seen any news about Apple changing this API, so hopefully its a bug in the beta and Apple hasn't changing functionality though. I'll investigate.

**Comment by caramdache** [comment]
> What do you mean here? Are you looking at podcast MP3 files? Or are they OPML or Mimir library files?

I meant individual MP3 files. I have been looking for a solution to import MP3 files, since iTunes could but Apple Postcast cannot. This is how I came across Mimir and I was under the impression that Mimir could import individual MP3 podcasts. Am I missing something?

**Comment by gdavis** [comment]
@caramdache there are some challenges in allowing just single MP3 files to be imported, as it relies on the metadata of the file to define how it would be identified by the app. Mimir is currently does not support importing individual MP3s, and I'll have to dig in and see what it might take to do so.

Complications could arise if you import individual files of a podcast; mp3 metadata does not typically include information like the RSS feed that points back to the podcast it came from, so I'd have to do some lookup work to figure out what podcast it might belong to. Some MP3 files might not have enough data provided to be identified either, so I'd have to determine how to handle that. 

The database right now just doesn't support single files very well, and would need some custom handling in the database to pull off. I'd like to add this feature, but there's technical hurdles I'll have to get over to handle this.

**Comment by caramdache** [comment]
@gdavis one such podcast can be found here. As far as I can see, there seems to be a lot of metadata, including a pointer to the source, title, author, etc.

https://media.radiofrance-podcast.net/podcast09/14503-17.04.2021-ITEMA_22639095-2021M23831E0052.mp3

**Comment by gdavis** [comment]
@caramdache thanks for that link, but even this file does not point back to the originating podcast RSS feed as far as I can tell, just where it was downloaded from. 

I'll likely need to design a new data structure that will allow files to be added without the RSS feed being loaded in, then devise a way to merge those files with the acutal RSS feed if a user added the feed after a few files.

I'd love to get this support in, but its going to be a bit since it does take a rather heavy lift of development to make those database changes and also support it with iCloud sync.

**Comment by caramdache** [comment]
@gdavis would it make development easier if the feed was already present in mimir and the mp3 files were to be added to that feed? 

In practice this is the case for me. The episodes are no longer present in the feed but still accessible and downloadable from the web page manually. It looks like maybe there could be no need for an additional data structure then. 

And in general case where there was no feed at all, couldn't one be created artificially to host these episodes, also avoiding the need for additional data structures?

**Comment by gdavis** [comment]
Hmm that's an interesting idea @caramdache. There'd still be some missing information that is provided by the RSS feed, but there could be an indicator saying that it is a local file and so some info would not show. 

This could potentially be a good middle-ground solution to support this. I'll see what I can do with this!

**Comment by gdavis** [comment]
Opened #226 to capture the feature for adding mp3 file support.

**Comment by gdavis** [comment]
I have been unable to reproduce this import issue on Ventura 13.1. Since this ticket is pretty dated now, I'm going to close until reproduced by myself or a user.
