### ISSUE TITLE
[BUG][iOS][UI] searching episodes seems to refresh the UI

### ISSUE THREAD

**Issue by ileacristian** [gdavis/Mimir-Feedback#21]
The header part of the page seems to refresh when changing the text from the search textfield.

Not sure it should do that.

https://user-images.githubusercontent.com/705971/159802497-4658ba9d-87ea-4403-a297-1363bd89fb5d.MOV

**Comment by gdavis** [comment]
It actually is refreshing that cell. The header cell is currently a collection view cell, and new search results apply a new snapshot which reloads the cell. I believe I can solve this by improving the snapshot update logic, or holding the header cell in property between refreshes, or some combination.

**Comment by gdavis** [comment]
This was fixed in the last release
