### ISSUE TITLE
[Bug][iOS]: Next Podcast Does Not Play in Continuous Playlist (Occurs in the Queue Also)

### ISSUE THREAD

**Issue by jeromekoehler** [gdavis/Mimir-Feedback#212]
### Are you sure this is a new issue?

- [X] I have confirmed this is a new issue

### iOS Version

16.0.3

### Device Model

iPhone 14 Pro Max

### App Version

1.0.3

### What happened?

When I let the podcasts play, some of them enter a state where the next podcast does not play in the continuous playlist until I press next or +15 seconds. This occurs when I let the device sit on my desk, while in CarPlay mode in my vehicle, or when charging.

### Bug prevalence

Occurs every time I use the application.

### How does it happen?

1. Open the App.
2. Select a podcast.
3. Play the podcasts in the queue or in the playlist.
4. When the podcast gets to the end, it does not automatically play the next podcast unless I press next manually or hit +15 seconds.

### Add screenshots or video.

![7420C88E-9B35-48E9-9C36-E9593D19E768_1_105_c](https://user-images.githubusercontent.com/1934568/196858710-60a4077c-d647-4603-ac81-0adab4999121.jpeg)
![F4DE93D0-7EC1-42A5-9B9B-C2CC65D1EAB6](https://user-images.githubusercontent.com/1934568/196858741-aca564e3-d5a2-4fb7-a7a4-7845c97904a0.png)

### Anything else?

No other information to add.

**Comment by jeromekoehler** [comment]
Other podcasts this occurs with: NPR's Up First, Mac Observer Daily Observations

**Comment by drallgood** [comment]
Same thing happens to me. 

Podcasts I've noticed it with: NPR News Now

**Comment by jeromekoehler** [comment]
After BBC Podcast finishes playing, this error popped up:

Playback Error
Mimir has failed to play the current episode. There may be an issue with the file, the network, or some other bug causing the issue.

Please try again or if the problem persists, report the issue to support@mimirpodcasts.app with the error below.

Player Error:
Data request is out of range of file.

Device Info:
App Version:    1.0.3
Build:          103
Device:         iPhone
Device Model:   iPhone
OS Version:     16.0.3
Locale:         en_US
Language:       en

**Comment by gdavis** [comment]
Thanks for adding to this issue @jeromekoehler and @drallgood. 

This is a known issue with the player for a while and has been quite tricky for me to track down. I'm currently tracking this issue in ticket #106 so I will close this issue and continue tracking it there. 

I hope to be able to tackle this soon, and I'm planning on making some other fixes to the audio player at the same time. Currently planning for this to be resolved within two releases as the next one will focus on fixing issues with downloads and updating subscriptions.

I appreciate the feedback!
