### ISSUE TITLE
Mimir is reporting all files as corrupted? 

### ISSUE THREAD

**Issue by drallgood** [gdavis/Mimir-Feedback#222]
### Are you sure this is a new issue?

- [X] I have confirmed this is a new issue

### iOS Version

16.3

### Device Model

iPhone 13 Pro Max

### App Version

1.1.0 (Testflight)

### What happened?

Playback Error
Mimir has failed to play the current episode. There may be an issue with the file, the network, or some other bug causing the issue.

Please try again or if the problem persists, report the issue to support@mimirpodcasts.app with the error below.

Player Error:
Data request is out of range of file.

Device Info:
App Version:    1.1.0
Build:          104
Device:         iPhone
Device Model:   iPhone
OS Version:     16.3
Locale:         en_US
Language:       en

### Bug prevalence

Currently it’s on every podcast 

### How does it happen?

Just opened the app this morning 

### Add screenshots or video.

![3623899F-65C6-4D9D-B0F4-A34936199BF9](https://user-images.githubusercontent.com/127142/209926666-01bc09d1-288e-4efd-bfc8-4354d6d4e40d.png)
![22672CE1-5E6F-436F-8972-D145A13885C5](https://user-images.githubusercontent.com/127142/209926671-43643281-4ed3-4ecf-a6e4-a2fcb8500c81.png)

### Anything else?

restarting the app doesn’t fix it. 
Also happens on podcasts the app just downloaded

**Comment by drallgood** [comment]
FYI:
Deleting all files & redownloading the podcasts seems to fix it

**Comment by gdavis** [comment]
Hi,thanks for reporting this @drallgood. Interesting issue for sure, it seems like the local files were perhaps removed. Do you know if you are low on disk space on that device? I wonder if the system tried removing some of it that I'm not accounting for.

Either way, I'm glad there was a workaround and I'll have to see if I can reproduce this. Let me know if you have any more info or if it happens again!

**Comment by drallgood** [comment]
Thanks @gdavis 
No storage shouldn't have been an issue. I have 150GB still available 😂
Maybe some network glitch where files got corrupted?

**Comment by gdavis** [comment]
@drallgood okay, cool. Just wanted to rule out the system doing something unexpected. A network issue could definitely be it, but I also am aware of a bug in the app that causes error icons to display for episodes that are not actually in error. Basically if one episode has an error, all episodes will show an error icon. This will be fixed in the next update, but might be what happened here as well. 

Here's the issue tracking that display bug, if this looks familiar at all: https://github.com/gdavis/Mimir-Feedback/issues/209

**Comment by drallgood** [comment]
@gdavis Yeah. That sounds very likely. I didn't try the other episodes because then the current one gets removed from the playlist. So if that one was corrupted then that might be explained by the other issue. 
Come to think of it, I did have some wifi issues yesterday. Maybe that's how that happened

**Comment by gdavis** [comment]
The latest version has a fix for the icons incorrectly showing an error state. Closing!
