### ISSUE TITLE
[macOS] File downloads all fail

### ISSUE THREAD

**Issue by MarkSealey** [gdavis/Mimir-Feedback#224]
Hi, since upgrading to Ventura (13.1),  _Mimir 1.5.1_ always reports an **error** (red exclamation point inside red circle) on any attempt to **download** any and all podcast episodes.

Have restarted and relaunched etc.

But the issue persists across all my feeds.

Examples are:

- In Our Time The Niebelungenlid https://podcasts.files.bbci.co.uk/b006qykl.rss
- The Ancients Spartacus https://rss.acast.com/the-ancients

I can successfully download everything as usual on the iOS _Mimir_.

Please ask if I can supply more details.

Have I missed a (system or app-specific) setting somewhere, please?

Hope you can fix this when you get a chance, please, Grant. Thanks!

**Comment by gdavis** [comment]
This will be tracked in ticket #225 

Closing this as a duplicate
