### ISSUE TITLE
[BUG][iOS] Tapping the downloaded checkmark does nothing

### ISSUE THREAD

**Issue by ileacristian** [gdavis/Mimir-Feedback#23]
There is a reverse loading animation that happens when you tap the already downloaded episode.

I was expecting to "delete" the episode if i would "unckeck" the checkmark.

https://user-images.githubusercontent.com/705971/159804579-668ece92-ff7e-408e-af10-40c2d55939ee.MOV

**Comment by gdavis** [comment]
Interesting effect isn't it? 

Along with fixing the reverse animation, I could also show an alert to confirm deleting the episode. Good suggestion.

**Comment by gdavis** [comment]
Fixed, will be released in build 82
