### ISSUE TITLE
[BUG][macOS] "In library" button does nothing

### ISSUE THREAD

**Issue by ileacristian** [gdavis/Mimir-Feedback#24]
After adding a new podcast to your library the "IN LIBRARY" button is clickable but does nothing.
I was expecting to remove the podcast from my library - like a toggle.
The iOS has the same behaviour of not doing anything - yet being tappable.

https://user-images.githubusercontent.com/705971/159805015-f382dd5d-1318-4364-b897-e6a49459b359.mov

**Comment by gdavis** [comment]
Hmm yeah my intention here was to give the button a disabled look and show that it is a one-way action. Not sure if I want to make this delete it from the library without changing the button text to indicate as such. I'm okay with the button not doing anything after its been added, it just might need a better UI state to indicate its no longer an active button.
