### ISSUE TITLE
[Bug][macOS]: Missing groups and podcasts in library

### ISSUE THREAD

**Issue by icejo123** [gdavis/Mimir-Feedback#240]
### Are you sure this is a new issue?

- [X] I have confirmed this is a new issue

### macOS Version

12.6.3

### Your Mac

MacBook Pro (15-inch, 2016)

### App Version

1.7.0

### What happened?

apparently the app updated on its own. suddenly I have only 1 group of feeds left. missing several groups with feeds. I need them back

### Bug prevalence

everytime i start up the app...

### How does it happen?

Open the app

### Add screenshots or video

cant show whats not there

### Anything else?

pls fix

**Comment by gdavis** [comment]
Hi @icejo123, that definitely does not sound good so I'll try and help you recover your library. Mimir makes backups of your library periodically so we need to find the latest good backup file and replace/merge with your existing library. 

1. To find backup files, you can use the Terminal app and type in this command:
> open /Users/{your username}/Library/Containers/com.grantdavisinteractive.Mimir/Data/Library/Application\ Support/com.grantdavisinteractive.Mimir/
2. This should open a directory in Finder that has our backup files. These are named like this:
<img width="324" alt="image" src="https://user-images.githubusercontent.com/110691/222152586-cfa012fd-d1e7-48e0-9d20-af852986517b.png">
3. Double-click the most recent "good" library file, and it will open Mimir and ask you to Replace or Merge with the backup file. Either should work, but I would try "Merge" first.
<img width="267" alt="image" src="https://user-images.githubusercontent.com/110691/222152830-2b872e51-c7e0-4171-b846-fe4e12f93b21.png">

This should restore the library back to a previous state. Please let me know how this fix works for you.

I'm also curious, did you recently add a new device to iCloud? I am trying to think of the ways this may have happened, and any clues could help!

Hope this helps.
