### ISSUE TITLE
[Bug][iOS]: No response when buy Mimir Pro or Premium Subscription

### ISSUE THREAD

**Issue by hechen** [gdavis/Mimir-Feedback#242]
### Are you sure this is a new issue?

- [X] I have confirmed this is a new issue

### iOS Version

16.3.1

### Device Model

iPhone 14 Pro Max

### App Version

1.2.0(121)

### What happened?

I downloaded the app, clicked "upgrade app", and then I clicked Buy Pro or try free for 7 days, there is no any response...

And I tried it on my iPad Pro and iPad mini, but the bug exists.

### Bug prevalence

Keep me from buying Pro on iPhone / iPad

### Add screenshots or video.

![4C74C236-AAAC-45C7-ABD0-EA5CF32E2012](https://user-images.githubusercontent.com/2241096/222845399-6aea6486-1a9e-40d8-8b4b-b7bb5b75ccc6.png)

**Comment by gdavis** [comment]
Hello @hechen! This was reported earlier today as well and I have already submitted a fix to the App Store. It will be fixed in version 1.3.0 as soon as it is approved by Apple.

Thanks for reporting it!
