### ISSUE TITLE
[iOS] export opml

### ISSUE THREAD

**Issue by jubishop** [gdavis/Mimir-Feedback#256]
I don't see any way to export my podcast list to opml.  It's hard for me to commit to trying a new podcast app if I don't see a decent escape hatch for the future.

**Comment by gdavis** [comment]
@jubishop yes, there is. From iOS, navigate to the Podcasts tab > tap the gear icon for Settings > and tap "Export Library > select Export as OPML.

From macOS, click the Library menu item, select Export Library > OPML file.

Hope that helps!

**Comment by jubishop** [comment]
Thanks!
