### ISSUE TITLE
[Bug][macOS]: Episode Titles Display with Overlapping Text 

### ISSUE THREAD

**Issue by fishcymbal** [gdavis/Mimir-Feedback#257]
### Are you sure this is a new issue?

- [X] I have confirmed this is a new issue

### macOS Version

Sonoma 14.4.1

### Your Mac

2020 Mac Mini M1

### App Version

1.8.3

### What happened?

When I search for a podcast and then click the button for "View Details," the previewed episode listing is jumbled with overlapping text. If I add the podcast to my library, it displays fine.

### Bug prevalence

Always when looking at new podcasts

### How does it happen?

1. Open the app
2. Click "Search" on the top left
3. Click "View Details" for any podcast

### Add screenshots or video

![titles](https://github.com/gdavis/Mimir-Feedback/assets/28100922/36f3f290-d311-4c96-9dac-6f390c70b498)

### Anything else?

Since this doesn't seem to be plaguing everyone, I realize this could be environmental to my machine only. It looks like the dates are overlapping with the titles. I checked the MacOS font size, and it looks like it's set at the default. If it's something I'm doing wrong, please let me know. Thanks!

**Comment by gdavis** [comment]
Hello @fishcymbal and thanks for making an issue on this. I don't think you're doing anything wrong and I'll check to see if I can reproduce it and get a fix out.

**Comment by gdavis** [comment]
fixed in gdavis/Mimir@7f5e89037616a2eb1f2f2e19786ca47e0dc220d1
