### ISSUE TITLE
[iOS] Top UI bar should have an opaque background

### ISSUE THREAD

**Issue by jubishop** [gdavis/Mimir-Feedback#260]
When I scroll down to read the details of a podcast episode, the bar at the top (which in this example says "Just Added") should have some sort of opaque background to keep it from visually mixing in with the text.  Attached screenshot should make the issue clear.  ![image](https://github.com/gdavis/Mimir-Feedback/assets/13165/97c83369-ae21-4aaf-96c4-5274ef3c0655)

**Comment by gdavis** [comment]
Fixed in next release
