### ISSUE TITLE
[Bug][macOS]: Episode refresh not happening automatically

### ISSUE THREAD

**Issue by SurlySteve** [gdavis/Mimir-Feedback#264]
### Are you sure this is a new issue?

- [X] I have confirmed this is a new issue

### macOS Version

Ventura 13.6.7

### Your Mac

iMac 21.5-inch, 2017

### App Version

1.8.3 (162)

### What happened?

New episodes of podcasts to which I have subscribed only appear if I manually refresh each podcast.

### Bug prevalence

Always

**Comment by gdavis** [comment]
Hello @SurlySteve, can you tell me what feed preference you have selected for when to update your feeds? This is found under Settings > Podcasts. Thanks!

**Comment by SurlySteve** [comment]
Good morning Grant,

Initially I had “Refresh feeds every” set at “Day” but have since switched it to “30 Minutes” and the issues seems to have resolved itself.

Cheers!

Steve

**Comment by gdavis** [comment]
Great!
