### ISSUE TITLE
[Bug][macOS]: Memory leak eventually eats all swap space (999 GB memory)

### ISSUE THREAD

**Issue by cquenelle** [gdavis/Mimir-Feedback#265]
### Are you sure this is a new issue?

- [X] I have confirmed this is a new issue

### macOS Version

Sonoma 14.5

### Your Mac

Mac Studio (M1 Ultra)

### App Version

1.8.3 (162)

### What happened?

When I leave the app running in the background for several days, MacOS eventually pops up a dialog saying that memory is used up and it shows me a list of apps and asks me to Force Quit one of them.  I can see in this window that Mimir is taking up 990-ish GB of memory.

### Bug prevalence

Possibly every time I leave the app running.

### How does it happen?

Open the app, read some podcast summaries, mark some episodes as "played", download some episodes.
Then I copy the downloaded folder for offline listening.
I leave the app running on my desktop mac.
Some number of days later I get a popup.

### Anything else?

If there is a way to take a stack dump I can do that the next time it fails.
I will track the size and see how often it increases, I'll add more details as I have them.

**Comment by cquenelle** [comment]
Experiment:
I started up Mimir from scratch, 113.8M memory size.
Then I browsed all my feeds.
- looked at summaries
- downloaded the episodes I want to listen to, as I browsed the summaries
- marked all episodes as "played" one feed at a time
Now the memory size is 406M.

**Comment by gdavis** [comment]
Hello @cquenelle. Can you export your library OPML and attach it to this ticket so I can try to reproduce this issue? 

There will be some expected memory usage when marking episodes as played since the app fetches episode records from the database in order to mark them as played. Obviously the app should not use up all your memory over time, so I'll need to do some testing to see how that might be happening. Unfortunately its a challenge to test a slow leak like that which manifests over several days  🙄

**Comment by cquenelle** [comment]
Here is the OPML in a zip file.
[podcasts.opml.zip](https://github.com/user-attachments/files/16465466/podcasts.opml.zip)

**Comment by cquenelle** [comment]
Any updates on this issue?

**Comment by gdavis** [comment]
@cquenelle yes! I have been able to find and fix this memory leak. I'm working on some other updates to go with it, but the next macOS release will fix this.

**Comment by gdavis** [comment]
The new update is now available with this fix

**Comment by cquenelle** [comment]
Which version is it fixed in?
I want to verify the fix, but I know the app store release process can take a while.
I installed 1.8.4 and I'll leave that running to check it.

**Comment by gdavis** [comment]
Yep, 1.8.4 released today is the one. Thanks for testing it out!

**Comment by cquenelle** [comment]
I verified this is fixed in 1.8.4.  Thanks for the fast response!
I love Mimir.  I download the podcasts I want, and the directory structure is nice and tidy.
I just copy the entire download directory onto a thumb drive or cloud drive and then I can listen anywhere I want.
Thanks for working on it!

**Comment by gdavis** [comment]
Very glad to hear it! I appreciate you verifying for me 🤗
