### ISSUE TITLE
[BUG] [UI] Corner radius mismatch issue when hovering search results/recommendations

### ISSUE THREAD

**Issue by ileacristian** [gdavis/Mimir-Feedback#3]
Issue is much more visible with the dark theme.
<img width="1250" alt="Screenshot 2022-03-23 at 19 10 34" src="https://user-images.githubusercontent.com/705971/159769946-1738caa6-1fb8-4617-b9be-28818782f045.png">

**Comment by gdavis** [comment]
https://imgur.com/a/iQIJh8W
