### ISSUE TITLE
[Improvement] [UI] Maybe use fixed width font for timestamps

### ISSUE THREAD

**Issue by ileacristian** [gdavis/Mimir-Feedback#4]
The time is jumping around when it changes because it isn't fixed width.

https://user-images.githubusercontent.com/705971/159773960-26d121db-9687-4e2e-a643-82e03956b282.mov

**Comment by gdavis** [comment]
I've reviewed the options using a mono spaced font and can say I'd rather keep the existing font than try to use a mono spaced one. I tried using the SF Mono font to keep it in the same font family as the rest of the fonts, and to me is a not a visual improvement and I find the changed font more distracting than the text moving slightly during playback.
