### ISSUE TITLE
[Bug][iOS]: Based on your top played podcasts just keeps loading on fresh install / account

### ISSUE THREAD

**Issue by Flpph** [gdavis/Mimir-Feedback#41]
### Are you sure this is a new issue?

- [X] I have confirmed this is a new issue

### iOS Version

15.4

### Device Model

iPhone XS

### App Version

1.0.0

### What happened?

On fresh install, if you go to the Discovery page the "Based on your top played podcasts" section just keeps loading and it just shows the skeleton view.

### Bug prevalence

Always

### How does it happen?

1. Open the app
2. Press the discover button at the bottom
3. See the bug

### Add screenshots or video.

![IMG_2794](https://user-images.githubusercontent.com/40421916/159970141-e8c59415-d63b-413e-8e5e-6c51fd0c8672.PNG)

### Anything else?

The app is awesome!

**Comment by gdavis** [comment]
Fixed, will be part of build iOS build 82
