### ISSUE TITLE
[Bug][iOS] Podcast episode list is not matching episode order

### ISSUE THREAD

**Issue by gdavis** [gdavis/Mimir-Feedback#55]
![image0](https://user-images.githubusercontent.com/110691/160218674-1cc25f1b-c49f-4ac4-b949-62212990573c.png)

The list seems to be ordered incorrectly for this podcast. Need to check the publish dates in the feed and confirm where this sorting issue may be coming from.

Reported by Moritz Ellerbrock  <me@elmoritz.eu>

```
App Version:    1.0.0
Build:          78
Device:         Elmo’s iPhone
Device Model:   iPhone
OS Version:     15.4
Locale:         en_DE
Language:       en
```

**Comment by elmoritz** [comment]
Sorry for the short Mail, was outside and though I send it right away.

The order does not change if you select most recent or order published.

Maybe the date is broken?
