### ISSUE TITLE
[iOS] Only start taking over the Audio-control, when Mimir is actually playing something and not when it is opened.

### ISSUE THREAD

**Issue by elmoritz** [gdavis/Mimir-Feedback#56]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I listen to Musik (e.g. spotify) and open Mimir and the audio cuts off because Mimir is taking over the control too soon.

**Describe the solution you'd like**
When I listen to Audio from another App than Mimir
and I jump into Mimir to add a podcast or find new Podcasts
Than I want to be able to continue listen to my audio
and not have Minir pause my Audio for no reason

**Describe alternatives you've considered**

**Additional context**

**Comment by Flpph** [comment]
I agree with this.. It was a bit frustrating for me when I was listening to music and just opened the app to look up a Podcast and the music stopped playing as I opened the app.

**Comment by gdavis** [comment]
Agreed, it should take over the audio session until it starts playing something. Will get it in queue to fix. Thanks guys!

**Comment by gdavis** [comment]
Fixed and will be available in release build 82
