### ISSUE TITLE
[iOS] Progress + No result on searching for a podcast

### ISSUE THREAD

**Issue by Flpph** [gdavis/Mimir-Feedback#57]
**Is your feature request related to a problem? Please describe.**
You can't see the progress of a search, just a white blank view. / Nothing shown on no result.

**Describe the solution you'd like**
I would like to have a Progress View telling me that the app is actually waiting for an API response. SwiftUI has a built in [ProgressView](https://developer.apple.com/documentation/swiftui/progressview), very easy to use. Also, when there's no result in the response, have a 'No result found' text or something.

**Additional context**
Both of these exist in the Mac app, just would be cool to have it in the iOS version.

**Comment by gdavis** [comment]
Yeah, there does need to be feedback here. One of the things I forgot to add before beta. Adding to the queue!

**Comment by gdavis** [comment]
"No Results" and a loader should display for:
- [x] Library Search
  - [x] Add button "Search for '{term}'" that brings the user to Discover and starts a search.
- [x] Discover Search

**Comment by gdavis** [comment]
This is now done and will be part of the next release!
