### ISSUE TITLE
[Bug][macOS][iOS]: Played episodes are reappearing as unplayed

### ISSUE THREAD

**Issue by SurlySteve** [gdavis/Mimir-Feedback#59]
### Are you sure this is a new issue?

- [X] I have confirmed this is a new issue

### macOS Version

macOS Monterey 12.3

### Your Mac

iMac (21.5-inch, 2017)

### App Version

1.5.0 (107)

### What happened?

In my Library episodes of podcasts which I have either listened to or marked as played are repopulating as not having been played.

### Bug prevalence

Almost always

### How does it happen?

I have my download of new episodes set to refresh every 30 minutes, but I don't think the episodes come back that frequently, maybe once a day.

### Anything else?

Nothing to add but thank you so much for creating a iOS podcast player that syncs with the macOS player and that doesn't suck like the player made by a non-citrus fruit company.

**Comment by gdavis** [comment]
Hello @SurlySteve, and thanks for filing this issue!

This is a known problem I've been tracking internally, and probably one of if not the highest priority concerns with the current apps right now. I'll be spending time this week working on a better solution to the playback status sync to address this.

**Comment by gdavis** [comment]
> Nothing to add but thank you so much for creating a iOS podcast player that syncs with the macOS player and that doesn't suck like the player made by a non-citrus fruit company.

😆 
Exactly what motivated me to start making Mimir years ago!

**Comment by SurlySteve** [comment]
I haven't noticed this occurring on my iPhone yet, although I do see the episodes there and wonder.  Here is an image of how it displays on my iMac.

![image](https://user-images.githubusercontent.com/102470092/160305976-2e05bb5c-1e89-4310-8506-88f45fa1da72.png)

**Comment by gdavis** [comment]
This has been fixed and is being released in iOS app version 80 & macOS version 108
