### ISSUE TITLE
[Bug][macOS]: Unknown OSStatus code

### ISSUE THREAD

**Issue by SurlySteve** [gdavis/Mimir-Feedback#67]
### Are you sure this is a new issue?

- [X] I have confirmed this is a new issue

### macOS Version

Monterey 12.3

### Your Mac

iMac (21.5-inch, 2017)

### App Version

1.5.0 (107)

### What happened?

I was listening to episodes which I had queued in "Up Next".  One episode had just finished and this error came up as Mimir was switching to the next episode.

### Bug prevalence

Rarely

### Anything else?

When I tried to clear the error and start the episode another "Playback Error" message stated "Error: Buffer provider is not yet ready to provide buffers."

![Screen Shot 2022-03-29 at 9 05 04 AM](https://user-images.githubusercontent.com/102470092/160619058-2421a734-51c8-4034-8f0e-b06bb718e379.png)

**Comment by gdavis** [comment]
Hmm this is a new one. Can you tell me what podcast and episode this occurred with? That error code basically means the format of the episode file is not supported, so it'd be great to know where it came from so I can check out what that file format is, and if can I adjust anything to allow it to play.

**Comment by SurlySteve** [comment]
I had just finished listening to episode "What's a Friend?" of the "Known with Dick Foth" podcast and the episode which caused the error was "Monday, March 28, 2022 - The Christian Science Monitor Daily".

**Comment by SurlySteve** [comment]
Another error under the same circumstances but different episodes.

![Screen Shot 2022-03-29 at 2 18 22 PM](https://user-images.githubusercontent.com/102470092/160678687-f28ce37d-80f1-408f-99c5-1e1ca9ececd7.png)

**Comment by gdavis** [comment]
Thanks for reporting this. The last screenshot looks like it might be a different issue with the error message being shown, but I'll put this in the queue and get it looked at.

**Comment by gdavis** [comment]
I've added some better error messaging for this error to indicate the file failed to load because it is not a supported audio filetype. Please let me know if you run into this in again in the next release @SurlySteve 

I've also fixed the error that pops up for the other image; the app was trying to delete a folder that was not on disk.
