### ISSUE TITLE
[Bug][iOS]: Drag and drop breaks tableview ui

### ISSUE THREAD

**Issue by ileacristian** [gdavis/Mimir-Feedback#69]
### Are you sure this is a new issue?

- [X] I have confirmed this is a new issue

### iOS Version

15.4

### Device Model

iphone 13pro

### App Version

1.0.0(79)

### What happened?

The tableview ui breaks

### Bug prevalence

always

### How does it happen?

1. long hold on a tableviewcell 
3. drag it like you would like to reorder the list 
4. 3. while still dragging the item, move your finger to the edge of the screen of another cell

### Add screenshots or video.

https://user-images.githubusercontent.com/705971/160698794-26fb948b-55b2-43cb-a07f-55e2455cf3ec.mov

**Comment by gdavis** [comment]
This has been fixed and is being released in iOS app version 80
