### ISSUE TITLE
[Bug][iOS]: Deleting multiple podcasts only delete the first one (per app session)

### ISSUE THREAD

**Issue by ileacristian** [gdavis/Mimir-Feedback#70]
### Are you sure this is a new issue?

- [X] I have confirmed this is a new issue

### iOS Version

15.4

### Device Model

iphone 13pro

### App Version

1.0.0(79)

### What happened?

I tried deleting multiple podcasts but when I reopened the only one item was deleted.

### How does it happen?

1. Have multiple podcasts
2. Delete a few podasts
3. Close the app
4. Reopen the app

Only one podcast gets deleted (one - or some, not sure)

This weird sync issue also happens if you add some podcasts, close the app and reopen it. Some podcasts will not be actually added after restart.

PS: Search also seems to be broken sometimes... can't really reproduce all the time. Might be a separate issue.

### Add screenshots or video.

https://user-images.githubusercontent.com/705971/160701171-25bcc8e0-f6c6-47d8-9301-7ae5fd9fb10f.mov

**Comment by gdavis** [comment]
This has been fixed and is being released in iOS app version 80
