### ISSUE TITLE
[Bug][iOS]: Only show downloaded episodes in "Downloaded" View

### ISSUE THREAD

**Issue by elmoritz** [gdavis/Mimir-Feedback#71]
### Are you sure this is a new issue?

- [X] I have confirmed this is a new issue

### iOS Version

iOS 15.4

### Device Model

iPhone 13 pro max

### App Version

1.0.0.(79)

### What happened?

I wanted to see what episodes where already downloaded, but as I was trying to find out why it had to download the file, I saw that in the downloaded Episode View it showed up, but as not downloaded.

### Add screenshots or video.

![image](https://user-images.githubusercontent.com/2924483/160899007-3d9306f7-e1e1-442a-b450-d769b0c027fb.png)

**Comment by gdavis** [comment]
Hmm looks like some values are not being updated when we delete episodes from disk, or the menu here isn't showing the right download state. Will investigate.

**Comment by gdavis** [comment]
Fixed, will be released in build 82
