### ISSUE TITLE
[Bug][iOS]: I can not enable "Sync Library"

### ISSUE THREAD

**Issue by elmoritz** [gdavis/Mimir-Feedback#74]
### Are you sure this is a new issue?

- [X] I have confirmed this is a new issue

### iOS Version

iOS 15.4

### Device Model

iPhone 13 pro max

### App Version

1.0.0.(79)

### What happened?

I tried to activate the "Sync Library" function and i can not enable it.

Video as Prove

### Add screenshots or video.

https://user-images.githubusercontent.com/2924483/160918929-520a8a80-9167-448e-88e9-12ec7d325d2e.MP4

**Comment by gdavis** [comment]
Related to #26 this is a bug where alerts were not displaying properly and has been fixed. The next TestFlight version will include this update, so let's close this issue and if this happens again, we'll reopen this and take a second look. Pretty sure this is fixed though.
