### ISSUE TITLE
[macOS] Add close button to the unlock banner in library sidebar

### ISSUE THREAD

**Issue by gdavis** [gdavis/Mimir-Feedback#80]
Give the user the option to close the unlock pro banner.

<img width="796" alt="image" src="https://user-images.githubusercontent.com/110691/160963942-b2bb2a42-c7bb-44b0-b541-66cd16889baa.png">

**Comment by gdavis** [comment]
A button to hide the banner has been added and will be part of build 109

**Comment by ghost** [comment]
Huge respect for adding this at the request of a user

**Comment by gdavis** [comment]
> Huge respect for adding this at the request of a user

Thanks! Trying to listen to the users :)
