### ISSUE TITLE
[macOS][BUG] Tapping cancel while in the IAP process will result in an error (see attached image)

### ISSUE THREAD

**Issue by ileacristian** [gdavis/Mimir-Feedback#9]
<img width="261" alt="Screenshot 2022-03-23 at 19 13 19" src="https://user-images.githubusercontent.com/705971/159777003-cb2e408d-a495-4e1f-b333-7bf57e8e01af.png">

**Comment by gdavis** [comment]
This should now be fixed with the rework of the in app purchases just released
