### ISSUE TITLE
[Bug][iOS][macOS]: Played episodes are reappearing as unplayed

### ISSUE THREAD

**Issue by SurlySteve** [gdavis/Mimir-Feedback#92]
### Are you sure this is a new issue?

- [X] I have confirmed this is a new issue

### macOS Version

Monterey 12.3.1

### Your Mac

iMac (21.5-inch, 2017)

### App Version

1.5.0 (109)

### What happened?

This issues has returned, I checked iOS Mimir and it was not occurring, at least not with this podcast.  The Timberline Church podcast has over 800 episodes and they have all been marked as unplayed.

![Screen Shot 2022-04-05 at 12 41 51 PM](https://user-images.githubusercontent.com/102470092/161807841-8c54daf3-344f-4d82-bfef-160d848d3d6a.png)

### Bug prevalence

Intermitten, more often than weekly...

**Comment by gdavis** [comment]
I'm still seeing these issues as well. Its been a nagging issue that I'll mark high priority and focus on this week.
