### ISSUE TITLE
[Bug][macOS][iOS]: Library is blank

### ISSUE THREAD

**Issue by SurlySteve** [gdavis/Mimir-Feedback#98]
### Are you sure this is a new issue?

- [X] I have confirmed this is a new issue

### macOS Version

Monterey 12.3.1

### Your Mac

iMac (21.5-inch, 2017)

### App Version

1.5.0 (109)

### What happened?

I was listening to episodes on my iPhone yesterday morning, in the afternoon when I went to resume my library was blank.  When I got home and looked at my iMac the Mimir icon did not indicate there were any unplayed episodes but in the Library each podcast had a number next to it.  When I selected a podcast it did not show any episodes to listen to.

I closed Mimir and reopened it but now my Library is blank.

![Screen Shot 2022-04-13 at 6 15 48 AM](https://user-images.githubusercontent.com/102470092/163159077-b46329be-8590-4b5a-8201-64459bcc322f.png)

### Bug prevalence

Always

### How does it happen?

1. Open the app

**Comment by gdavis** [comment]
Hey @SurlySteve, this is definitely a bad one. I have a few questions for you just so I understand the order things happened.

- It looks like the library went blank after only using the iPhone, not after a sync with the mac. Then the empty library you saw on iPhone copied over to the Mac and also cleared out that library. Is that right?
- Had the library already been synced with the mac before this? 
- Were any changes made to your iCloud settings? Either changing files in the iCloud drive or logging into a different account? I'm assuming no or you would mention it, just ruling this out.
- Would it be possible to zip and attach a copy of the corrupted library file to this issue? It can be found under your `iCloud Drive/Mimir/library.mimir` directory. 

One thing to try, I built in automatic backups to the library file that you can try to restore your from them. 
1. Open up Mimir on your mac, go to About, and quickly click the app icon 9 times. This is a debugging action that will open Finder and bring you to the support files in the app. 
2. You should see a few files here named something like `library-backup-2022-04-07T052632.mimir`. 
3. Open the most recent in Mimir and you can restore your library from this backup file. 
4. If that backup file doesn't have the correct content, perhaps after creating a backup from the empty library, try one of the older backup files.

Let me know if you have any other info on this one since it is very high priority to fix. I'm working on iCloud sync issues this week, so if we can figure out how to make this happen consistently I have a much greater chance of fixing it.

My best guess right now is that the iPhone device got into a conflicted state, or the `library.json` file within the library package got corrupted, causing that file to have an empty library list. Then when Mimir opened and tried to sync the local data with the cloud-synced library file, it thought podcasts had been deleted and ended up removing them. I'll be working to try and reproduce this this week.

**Comment by SurlySteve** [comment]
Hey Grant,

Yes, I was using iOS Mimir at work yesterday morning and then later when I tried to listen again on my iPhone the Library was blank.  I think my setting are set for iCloud syncing.

It had been syncing properly until recently, but yesterday was the first day i’ve had to go back into the office so most of my Mimir use has been limited to macOS.

When I noticed the Library was blank I tried to download the Mimir information from the iCloud but that didn’t resolve the issue.  I have not messed with the setting since just after TestFlight installed Mimir on my iPhone and iPad.

Absolutely!  Here you go.



I have not been able to successfully launch the debugging action…

Cheers!

Steve

**Comment by gdavis** [comment]
Thanks for the answers, Steve! Can you try attaching the library file again, it doesn't look like it was attached. You probably need to compress it into a ZIP first before Github will accept it.

If clicking the logo in the About window isn't working for you, you can try to manually open up the application support directory to find the backups from Terminal with the following commands

> open '/Users/yourusernameLibrary/Containers/com.grantdavisinteractive.Mimir/Data/Library/Application\ Support/'

From finder, locate the `com.grantdavisinteractive.Mimir` directory view it. From here you should be able to see the backup library files. 

It looks like I need to use a different extension for the library file. Using `mimir` is conflicting with the folder name `com.grantdavisinteractive.Mimir`, making it not open. I'll track that separately here #99 .

**Comment by SurlySteve** [comment]
Grant,

Here goes… I right-clicked on the “library.mimir” file and selected compress, this process saved the file as “library.mimir.zip” and that is what I am trying to send.

I am not having much luck with Terminal, I copied your command, changed it to match my user name and received this message:

The file /Users/Steve/Library/Containers/com.grantdavisinteractive.Mimir/Data/Library/Application/Support does not exist.

I am found my way to the folder but do not see any back up files.

**Comment by gdavis** [comment]
@SurlySteve it looks like the path for the "Application Support" directory is incorrect. It should have a space there, so make sure you are using quotes for the full path, like this:

> open '/Users/Steve/Library/Containers/com.grantdavisinteractive.Mimir/Data/Library/Application Support'

Try that out!

**Comment by gdavis** [comment]
> I am found my way to the folder but do not see any back up files.

Hmm well thats no good. Are you sure you are in the 'com.grantdavisinteractive.Mimir' directory within the Application Support directory? You should also see files such as "config-v2.json" and a `library.sqlite` file. Are you seeing those?

**Comment by gdavis** [comment]
I also still don't see the file being attached, can you directly mail it to me at `support@mimirpodcasts.app`?

**Comment by SurlySteve** [comment]
Grant

No I do not see either of these files.

Steve

**Comment by gdavis** [comment]
@SurlySteve can you try to run this command from Terminal? It will search your computer for any existing backup files that may be on your mac:

> find . -name 'library-backup*.mimir'

If it prints out a file location like this:
> ./Library/Containers/com.grantdavisinteractive.Mimir/Data/Library/Application Support/com.grantdavisinteractive.Mimir/library-backup-2022-04-13.mimir

you can then try to open that file in Mimir and have it restore the library from that backup file:

> open './Library/Containers/com.grantdavisinteractive.Mimir/Data/Library/Application Support/com.grantdavisinteractive.Mimir/library-backup-2022-04-13.mimir'

Remember to add the `'` to the start and end of the path or you will get a "does not exist" error. Please try that and let me know if you are able to restore.

**Comment by SurlySteve** [comment]
Grant

Success!  Thank you.

Here are the results of the command:

***@***.*** ~ % find . -name 'library*.mimir'
find: ./Library/Application Support/MobileSync: Operation not permitted
find: ./Library/Application Support/com.apple.siri.remembers: Operation not permitted
find: ./Library/Application Support/CallHistoryTransactions: Operation not permitted
find: ./Library/Application Support/CloudDocs/session/db: Operation not permitted
find: ./Library/Application Support/com.apple.sharedfilelist: Operation not permitted
find: ./Library/Application Support/Knowledge: Operation not permitted
find: ./Library/Application Support/com.apple.TCC: Operation not permitted
find: ./Library/Application Support/FileProvider: Operation not permitted
find: ./Library/Application Support/com.apple.avfoundation/Frecents: Operation not permitted
find: ./Library/Application Support/CallHistoryDB: Operation not permitted
find: ./Library/Assistant/SiriVocabulary: Operation not permitted
find: ./Library/Autosave Information: Operation not permitted
find: ./Library/IdentityServices: Operation not permitted
find: ./Library/Messages: Operation not permitted
find: ./Library/HomeKit: Operation not permitted
find: ./Library/Sharing: Operation not permitted
find: ./Library/Mail: Operation not permitted
find: ./Library/DuetExpertCenter: Operation not permitted
find: ./Library/com.apple.internal.ck: Operation not permitted
find: ./Library/Accounts: Operation not permitted
find: ./Library/Safari: Operation not permitted
find: ./Library/Biome: Operation not permitted
find: ./Library/Shortcuts: Operation not permitted
./Library/Mobile Documents/iCloud~com~grantdavisinteractive~mimir/Documents/library.mimir
find: ./Library/Suggestions: Operation not permitted
find: ./Library/Group Containers/group.com.apple.icloud.drive: Operation not permitted
find: ./Library/Group Containers/group.com.apple.secure-control-center-preferences: Operation not permitted
find: ./Library/Group Containers/group.com.apple.notes: Operation not permitted
find: ./Library/Containers/com.apple.VoiceMemos: Operation not permitted
find: ./Library/Containers/com.apple.archiveutility: Operation not permitted
find: ./Library/Containers/com.apple.Home: Operation not permitted
find: ./Library/Containers/com.apple.Safari: Operation not permitted
find: ./Library/Containers/com.apple.icloud.drive.fileprovider: Operation not permitted
./Library/Containers/com.grantdavisinteractive.Mimir/Data/Library/Application Support/com.grantdavisinteractive.Mimir/library-backup-2022-04-12.mimir
./Library/Containers/com.grantdavisinteractive.Mimir/Data/Library/Application Support/com.grantdavisinteractive.Mimir/library-backup-2022-04-13.mimir
./Library/Containers/com.grantdavisinteractive.Mimir/Data/Library/Application Support/com.grantdavisinteractive.Mimir/library-backup-2022-04-11.mimir
find: ./Library/Containers/com.apple.iChat: Operation not permitted
find: ./Library/Containers/com.apple.CloudDocs.MobileDocumentsFileProvider: Operation not permitted
find: ./Library/Containers/com.apple.mail: Operation not permitted
find: ./Library/Containers/com.apple.Notes: Operation not permitted
find: ./Library/Containers/com.apple.news: Operation not permitted
find: ./Library/Containers/com.apple.corerecents.recentsd/Data/Library/Recents: Operation not permitted
find: ./Library/Containers/com.apple.stocks: Operation not permitted
find: ./Library/PersonalizationPortrait: Operation not permitted
find: ./Library/Metadata/CoreSpotlight: Operation not permitted
find: ./Library/Metadata/com.apple.IntelligentSuggestions: Operation not permitted
find: ./Library/Cookies: Operation not permitted
find: ./Library/CoreFollowUp: Operation not permitted
find: ./Library/StatusKit: Operation not permitted
find: ./Library/Caches/com.apple.HomeKit: Operation not permitted
find: ./Library/Caches/CloudKit: Operation not permitted
find: ./Library/Caches/com.apple.Safari: Operation not permitted
find: ./Library/Caches/com.apple.findmy.imagecache: Operation not permitted
find: ./Library/Caches/com.apple.findmy.fmfcore: Operation not permitted
find: ./Library/Caches/FamilyCircle: Operation not permitted
find: ./Library/Caches/com.apple.homed: Operation not permitted
find: ./Library/Caches/com.apple.findmy.fmipcore: Operation not permitted
find: ./Library/Caches/com.apple.ap.adprivacyd: Operation not permitted
find: ./.Trash: Operation not permitted

**Comment by gdavis** [comment]
Phew! Very glad we were able to restore that library for you. Now I'll work on making sure it doesn't happen again 🙄

**Comment by gdavis** [comment]
Hi @SurlySteve – I just released a new version for both iOS and macOS that completely reworks the iCloud sync feature to eliminate these issues you've been seeing. I'm pretty confident this will work much better than the previous version, so please give it a shot and let me know how everything works for you!

Thanks again for the feedback.

**Comment by SurlySteve** [comment]
Thanks Grant!  I just updated them and will give them a run tomorrow.

Cheers!

Steve
